language: go

go:
  - "1.13"

env:
  matrix:
    - FOLDER="car" BUILD_PARAM="GOOS=linux GOARCH=arm GOARM=6"
    - FOLDER="interface" BUILD_PARAM="GOOS=windows GOARCH=amd64"

script:
  - cd $FOLDER
  - env $BUILD_PARAM go build